### ISSUE TITLE
Create an Initial Page for the material choice  

### ISSUE THREAD

**Issue by soumilk** [AkshitOstwal/CodeForVision#3]
This would be the first page of the project, in this make a list containing all the items which are manufactured by ITC. 
Page Layout: 
* Heading of the project 
   * Make three categories of the items i.e Solid, powder, liquid and in each of them make a list of items made by ITC.
   * Make the lists scrollable and also input some demo data in it. Later we will fetch data from the database.
   * <strong>Add an option for the new product </strong> In the case of a new product it will take the user to the input form which will intake all the properties mentioned in the form.

Try to make this page look good.

**Comment by AkshitOstwal** [comment]
Had been made closing this issue
